// Ant Design configuration exports
export { default as AntdProvider, antdTheme } from './antd-config';
export { default as StyledComponentsRegistry } from './AntdRegistry';
export { default as defaultLocale, locales } from './antd-locale';

// Ant Design utilities exports
export * from './antd-utils';

// Re-export commonly used Ant Design components for convenience
export {
  Button,
  Card,
  Table,
  Form,
  Input,
  Select,
  DatePicker,
  Upload,
  Modal,
  Drawer,
  Tooltip,
  Popconfirm,
  Dropdown,
  Menu,
  Layout,
  Row,
  Col,
  Space,
  Divider,
  Typography,
  Tag,
  Badge,
  Avatar,
  Spin,
  Alert,
  Progress,
  Steps,
  Tabs,
  Collapse,
  Timeline,
  Tree,
  TreeSelect,
  Cascader,
  AutoComplete,
  Switch,
  Checkbox,
  Radio,
  Rate,
  Slider,
  InputNumber,
  TimePicker,
  Transfer,
  Pagination,
  BackTop,
  Anchor,
  Affix,
  Breadcrumb,
  ConfigProvider,
  App,
} from 'antd';

// Re-export commonly used icons
export {
  SearchOutlined,
  EditOutlined,
  DeleteOutlined,
  PlusOutlined,
  DownloadOutlined,
  UploadOutlined,
  EyeOutlined,
  SettingOutlined,
  UserOutlined,
  HomeOutlined,
  DashboardOutlined,
  TableOutlined,
  BarChartOutlined,
  LineChartOutlined,
  PieChartOutlined,
  FileOutlined,
  FolderOutlined,
  SaveOutlined,
  CloseOutlined,
  CheckOutlined,
  InfoCircleOutlined,
  ExclamationCircleOutlined,
  QuestionCircleOutlined,
  WarningOutlined,
  LoadingOutlined,
  ReloadOutlined,
  FilterOutlined,
  SortAscendingOutlined,
  SortDescendingOutlined,
  RocketOutlined,
  CheckCircleOutlined,
} from '@ant-design/icons'; 